---
- name: Kubernetes | Ensure required directory exist
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ bin_dir }}"
    - "{{ systemd_units_dir }}"
    - "{{ kubelet_systemd_dropin_dir }}"

- name: Kubernetes | Get Kubernetes binaries
  get_url:
    url: "{{ kubernetes_binaries_url }}/{{ item }}"
    mode: 0755
    dest: "{{ bin_dir }}/{{ item }}"
    force: yes
  with_items: "{{ kubernetes_binaries }}"
  notify: "restart kubelet"

- name: Kubernetes | Get crictl
  unarchive:
    src: "{{ crictl_release_url }}"
    dest: "{{ bin_dir }}"
    remote_src: yes

- name: Kubernetes | Install crictl config
  template:
    src: crictl.yaml.j2
    dest: /etc/crictl.yaml
    mode: 0644

- name: Kubernets | Install crictl completion
  shell: "{{ bin_dir }}/crictl completion > /etc/bash_completion.d/crictl"
  ignore_errors: True
  when: ansible_distribution in ["CentOS","RedHat", "Ubuntu", "Debian"]

- name: Kubernetes | Get Kubelet config file
  copy:
    content: "{{ item | regex_replace( '/usr/bin', bin_dir) }}"
    dest: "{{ kubelet_systemd_unit }}"
  loop: "{{ lookup('url', kubelet_systemd_unit_url, split_lines=False, wantlist=True ) }}"
  notify: "restart kubelet"

- name: Kubernetes | Get Kubeadm drop-in file
  copy:
    content: "{{ item | regex_replace( '/usr/bin', bin_dir) }}"
    dest: "{{ kubeadm_systemd_dropin_file }}"
  loop: "{{ lookup('url', kubeadm_systemd_dropin_url, split_lines=False, wantlist=True ) }}"
  notify: "restart kubelet"

- meta: flush_handlers

- name: Kubernetes | Ensure Kubelet is enabled and running
  systemd:
    state: started
    name: kubelet.service
    enabled: yes
